plugins { id 'com.android.application' }

android {
    namespace 'com.atrangi.documentworkspace'
    compileSdk 35

    defaultConfig {
        applicationId 'com.atrangi.documentworkspace'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '7.1-android-1'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies { implementation 'androidx.core:core:1.15.0' }
